### PR TITLE
Bring route to front on hover

### PR DESCRIPTION
**Pull request by tomchadwin**

### CODE REVIEW

**Comment by tomchadwin** [comment]
Not quite there - apologies.

**Comment by tomchadwin** [comment]
OK, now good to go, I think.

**Comment by walkermatt** [comment]
I think we should also set the zIndex of the start point. It currently gets hidden by the route on hover.

**Comment by tomchadwin** [comment]
I've added that to the codebase, but my local version is now hanging. If you can check this branch yourself, that would be great - not sure what issue I have.

**Comment by tomchadwin** [comment]
All working now, and I think looks good to go.

**Pull request merged**
